/**
 * Renders the GitHub Actions workflow that puts new issues and PRs into the
 * triage queue by applying the queue label. Pure, so `pxt automate` and the
 * tests share it.
 */
export interface WorkflowOptions {
  /** Queue label to apply. */
  readonly label: string
  readonly issues: boolean
  readonly pullRequests: boolean
  /** Skip the changesets "Version Packages" release PR. */
  readonly excludeChangesets: boolean
  /** Skip items opened by bots (dependabot, renovate, github-actions, …). */
  readonly excludeBots: boolean
  /** Label PRs only once they leave draft. */
  readonly skipDrafts: boolean
  /** Create the label if the repository does not have it yet. */
  readonly ensureLabel: boolean
}

export const DEFAULT_WORKFLOW_OPTIONS: WorkflowOptions = {
  label: "triage",
  issues: true,
  pullRequests: true,
  excludeChangesets: true,
  excludeBots: true,
  skipDrafts: false,
  ensureLabel: true
}

export const WORKFLOW_FILE = "triage-label.yml"

const yamlString = (s: string): string => JSON.stringify(s)

export const renderWorkflow = (o: WorkflowOptions): string => {
  const triggers: Array<string> = []
  if (o.issues) triggers.push("  issues:\n    types: [opened, reopened]")
  if (o.pullRequests) {
    const types = o.skipDrafts ? "[opened, reopened, ready_for_review]" : "[opened, reopened, ready_for_review]"
    // pull_request_target runs with a write token for fork PRs too. Safe here:
    // the job never checks out or executes the PR's code.
    triggers.push(`  pull_request_target:\n    types: ${types}`)
  }

  const conditions: Array<string> = []
  if (o.excludeChangesets) {
    conditions.push("!(github.event_name == 'pull_request_target' && github.event.pull_request.user.login == 'github-actions[bot]' && startsWith(github.event.pull_request.head.ref, 'changeset-release/'))")
  }
  if (o.excludeBots) {
    conditions.push("!endsWith(github.actor, '[bot]')")
  }
  if (o.pullRequests && o.skipDrafts) {
    conditions.push("!(github.event_name == 'pull_request_target' && github.event.pull_request.draft)")
  }
  const ifLine = conditions.length ? `    if: ${conditions.length === 1 ? conditions[0] : conditions.map((c) => `(${c})`).join(" && ")}\n` : ""

  const ensure = o.ensureLabel
    ? `      - name: Make sure the label exists
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          gh api --silent "repos/$GITHUB_REPOSITORY/labels/${encodeURIComponent(o.label)}" \\
            || gh api --silent -X POST "repos/$GITHUB_REPOSITORY/labels" \\
                 -f name=${yamlString(o.label)} -f color="FBCA04" -f description="Needs triage"
`
    : ""

  return `# Generated by px-triage (\`pxt automate\`). Edit freely.
#
# New issues and pull requests get the ${yamlString(o.label)} label so they show up in
# the px-triage queue; px-triage removes the label as each item is handled.
name: Label new items for triage

on:
${triggers.join("\n")}

permissions:
  issues: write
  pull-requests: write

jobs:
  label:
${ifLine}    runs-on: ubuntu-latest
    steps:
${ensure}      - name: Add the label
        env:
          GH_TOKEN: \${{ github.token }}
          NUMBER: \${{ github.event.issue.number || github.event.pull_request.number }}
        run: |
          gh api --silent -X POST "repos/$GITHUB_REPOSITORY/issues/$NUMBER/labels" \\
            -f "labels[]=${o.label}"
`
}
